INSERT INTO ACCESS_POINT  ( ACCESS_POINT_ID , NAME ) VALUES (1, 'AP1');
INSERT INTO ACCESS_POINT  ( ACCESS_POINT_ID , NAME ) VALUES (2, 'AP2');
INSERT INTO ACCESS_POINT  ( ACCESS_POINT_ID , NAME ) VALUES (3, 'AP3');
