-- $2y$10$P7im4OMw6hsnPWLpJ1nVKup1jlEFsLIek9D3lglmZv.Tq05GDEhMS -> passwd
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Admin', 'Istrator', '$2y$10$P7im4OMw6hsnPWLpJ1nVKup1jlEFsLIek9D3lglmZv.Tq05GDEhMS', 'admin', 'admin', '2016-01-01 00:00:00');
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('admin', 'ADMIN');
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('admin', 'USER');
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Susi', 'Kaufgern', '$2y$10$P7im4OMw6hsnPWLpJ1nVKup1jlEFsLIek9D3lglmZv.Tq05GDEhMS', 'user1', 'admin', '2016-01-01 00:00:00');
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('user1', 'GARDENER');
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('user1', 'USER');
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Max', 'Mustermann', '$2y$10$P7im4OMw6hsnPWLpJ1nVKup1jlEFsLIek9D3lglmZv.Tq05GDEhMS', 'user2', 'admin', '2016-01-01 00:00:00');
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('user2', 'USER');
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'Elvis', 'The King', '$2y$10$P7im4OMw6hsnPWLpJ1nVKup1jlEFsLIek9D3lglmZv.Tq05GDEhMS', 'elvis', 'elvis', '2016-01-01 00:00:00');
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('elvis', 'ADMIN');
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('elvis', 'USER');
INSERT INTO USERX_USER_ROLE (USERX_USERNAME, ROLES) VALUES ('elvis', 'GARDENER');
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'FirstName1', 'LastName1', '$2y$10$P7im4OMw6hsnPWLpJ1nVKup1jlEFsLIek9D3lglmZv.Tq05GDEhMS', 'Userx1', 'elvis', '2016-01-01 00:00:00');
INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE) VALUES(TRUE, 'FirstName2', 'LastName2', '$2y$10$P7im4OMw6hsnPWLpJ1nVKup1jlEFsLIek9D3lglmZv.Tq05GDEhMS', 'Userx2', 'elvis', '2016-01-01 00:00:00');

-- AccessPoint

INSERT INTO ACCESS_POINT ( ACCESS_POINT_ID, NAME, MAKE_CONNECTION) VALUES (1, 'AccessPoint1', FALSE);
INSERT INTO ACCESS_POINT ( ACCESS_POINT_ID, NAME, MAKE_CONNECTION) VALUES (2, 'AccessPoint2', FALSE);
INSERT INTO ACCESS_POINT ( ACCESS_POINT_ID, NAME, MAKE_CONNECTION) VALUES (3, 'AccessPoint3', FALSE);

-- SensorStation
INSERT INTO SENSOR_STATION ( SENSOR_STATION_ID, ACCESS_POINT_ID, GAERTNER_USERNAME , NAME, UPDATE_INTERVAL ) VALUES (1, 1, 'user1', 'SensorStation1', 300);
INSERT INTO SENSOR_STATION ( SENSOR_STATION_ID, ACCESS_POINT_ID, GAERTNER_USERNAME , NAME, UPDATE_INTERVAL ) VALUES (2, 1, 'elvis', 'SensorStation2', 10);
INSERT INTO SENSOR_STATION ( SENSOR_STATION_ID, ACCESS_POINT_ID, GAERTNER_USERNAME , NAME, UPDATE_INTERVAL ) VALUES (3, 2, 'elvis', 'SensorStation4', 15);
INSERT INTO SENSOR_STATION ( SENSOR_STATION_ID, ACCESS_POINT_ID, GAERTNER_USERNAME , NAME, UPDATE_INTERVAL ) VALUES (4, 3, null, 'SensorStation5', 20);

-- Devices
INSERT INTO BLUETOOTH_DEVICE(BLUETOOTH_DEVICE_ID, CONNECTED, DEVICE_NAME, SHOULD_CONNECT, ACCESS_POINT_ACCESS_POINT_ID) values (1, 0, 'Station1_LE', 0, 1);
INSERT INTO BLUETOOTH_DEVICE(BLUETOOTH_DEVICE_ID, CONNECTED, DEVICE_NAME, SHOULD_CONNECT, ACCESS_POINT_ACCESS_POINT_ID) values (2, 0, 'Station2_LE', 0, 1);
